const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json;charset=utf-8'}});
function cors(env){return{'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Headers':'Authorization, Content-Type, X-File-Name, X-Record-Count','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Max-Age':'86400'}}
function withCors(r,env){const h=new Headers(r.headers);Object.entries(cors(env)).forEach(([k,v])=>h.set(k,v));return new Response(r.body,{status:r.status,headers:h})}
function auth(req,env){return req.headers.get('Authorization')===`Bearer ${env.API_KEY}`}
function safeName(v){return (v||'output.csv').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,180)}
export default{async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(env)});if(!auth(req,env))return withCors(json({error:'Unauthorized'},401),env);const u=new URL(req.url);try{
if(u.pathname==='/api/csv'&&req.method==='POST'){const body=await req.arrayBuffer();if(!body.byteLength)return withCors(json({error:'Empty CSV'},400),env);const id=crypto.randomUUID(),name=safeName(req.headers.get('X-File-Name')),created=new Date().toISOString(),key=`csv/${created.slice(0,7)}/${id}_${name}`,count=Number(req.headers.get('X-Record-Count')||0);await env.CSV_BUCKET.put(key,body,{httpMetadata:{contentType:'text/csv; charset=utf-8'}});await env.DB.prepare('INSERT INTO csv_files(id,object_key,file_name,record_count,size_bytes,created_at) VALUES(?,?,?,?,?,?)').bind(id,key,name,count,body.byteLength,created).run();return withCors(json({id,fileName:name,recordCount:count,size:body.byteLength,createdAt:created},201),env)}
if(u.pathname==='/api/csv'&&req.method==='GET'){const q=await env.DB.prepare('SELECT id,file_name AS fileName,record_count AS recordCount,size_bytes AS size,created_at AS createdAt FROM csv_files ORDER BY created_at DESC LIMIT ?').bind(Math.min(Number(u.searchParams.get('limit')||100),500)).all();return withCors(json({items:q.results}),env)}
const d=u.pathname.match(/^\/api\/csv\/([^/]+)\/download$/);if(d&&req.method==='GET'){const row=await env.DB.prepare('SELECT * FROM csv_files WHERE id=?').bind(d[1]).first();if(!row)return withCors(json({error:'Not found'},404),env);const o=await env.CSV_BUCKET.get(row.object_key);if(!o)return withCors(json({error:'Object missing'},404),env);return withCors(new Response(o.body,{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${safeName(row.file_name)}"`}}),env)}
const one=u.pathname.match(/^\/api\/csv\/([^/]+)$/);if(one&&req.method==='DELETE'){const row=await env.DB.prepare('SELECT object_key FROM csv_files WHERE id=?').bind(one[1]).first();if(!row)return withCors(json({error:'Not found'},404),env);await env.CSV_BUCKET.delete(row.object_key);await env.DB.prepare('DELETE FROM csv_files WHERE id=?').bind(one[1]).run();return withCors(json({deleted:true,id:one[1]}),env)}
if(u.pathname==='/api/csv/latest/download'&&req.method==='GET'){const name=u.searchParams.get('fileName');const row=name?await env.DB.prepare('SELECT * FROM csv_files WHERE file_name=? ORDER BY created_at DESC LIMIT 1').bind(name).first():await env.DB.prepare('SELECT * FROM csv_files ORDER BY created_at DESC LIMIT 1').first();if(!row)return withCors(json({error:'Not found'},404),env);const o=await env.CSV_BUCKET.get(row.object_key);return withCors(new Response(o.body,{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${safeName(row.file_name)}"`}}),env)}
return withCors(json({error:'Not found'},404),env)}catch(e){console.error(e);return withCors(json({error:'Internal error',message:e.message},500),env)}}}
