const $=id=>document.getElementById(id),fileInput=$('fileInput'),processBtn=$('processBtn'),spinner=$('spinner'),errorBox=$('errorBox'),resultBox=$('resultBox'),recordCount=$('recordCount'),resultTable=$('resultTable'),downloadBtn=$('downloadBtn'),startNameInput=$('startName'),prefixInput=$('fileNamePrefix'),endNameInput=$('endName'),fileNamePreview=$('fileNamePreview'),archiveStatus=$('archiveStatus'),refreshHistoryBtn=$('refreshHistoryBtn'),historyTable=$('historyTable'),historyError=$('historyError');
const cfg=window.APP_CONFIG||{};let pyodide=null,lastCSV='',lastFileName='output.csv',processing=false;
const apiHeaders=extra=>({'Authorization':`Bearer ${cfg.apiKey}`,...extra});
function outputName(){return`${startNameInput.value||''}${prefixInput.value||''}${endNameInput.value||''}.csv`}function showError(m){errorBox.textContent=m;errorBox.classList.remove('hidden')}function setBusy(v,t='Elabora file'){processing=v;spinner.hidden=!v;spinner.classList.toggle('hidden',!v);spinner.style.display=v?'inline-block':'none';processBtn.disabled=v;processBtn.textContent=v?t:'Elabora file'}
function render(records){resultTable.innerHTML='';if(!records.length)return;const h=Object.keys(records[0]),hr=document.createElement('tr'),head=document.createElement('thead');h.forEach(x=>{const th=document.createElement('th');th.textContent=x;hr.appendChild(th)});head.appendChild(hr);resultTable.appendChild(head);const body=document.createElement('tbody');records.slice(0,200).forEach(r=>{const tr=document.createElement('tr');h.forEach(x=>{const td=document.createElement('td');td.textContent=r[x]??'';tr.appendChild(td)});body.appendChild(tr)});resultTable.appendChild(body)}
async function pythonInit(){pyodide=await loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.28.3/full/'});await pyodide.loadPackage('micropip');const m=pyodide.pyimport('micropip');try{await m.install('openpyxl')}finally{m.destroy()}const r=await fetch('./python/finrep_processor.py',{cache:'no-cache'});if(!r.ok)throw Error(`Motore Python non trovato: HTTP ${r.status}`);await pyodide.runPythonAsync(await r.text());return pyodide}const pythonReady=pythonInit();pythonReady.catch(console.error);
async function archiveCSV(csv,name,count){if(!cfg.apiBaseUrl||cfg.apiBaseUrl.includes('YOUR-WORKER')||!cfg.apiKey||cfg.apiKey==='CHANGE_ME'){archiveStatus.textContent='CSV generato. Configura APP_CONFIG per abilitarne lo storico.';return}archiveStatus.textContent='Salvataggio nello storico...';const r=await fetch(`${cfg.apiBaseUrl}/api/csv`,{method:'POST',headers:apiHeaders({'Content-Type':'text/csv;charset=utf-8','X-File-Name':name,'X-Record-Count':String(count)}),body:csv});if(!r.ok)throw Error(`Salvataggio fallito: HTTP ${r.status}`);archiveStatus.textContent='CSV salvato nello storico.';await loadHistory()}
function bytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
async function apiDownload(id,name){const r=await fetch(`${cfg.apiBaseUrl}/api/csv/${id}/download`,{headers:apiHeaders()});if(!r.ok)throw Error(`Download fallito: HTTP ${r.status}`);const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
async function removeCSV(id){if(!confirm('Eliminare definitivamente questo CSV?'))return;const r=await fetch(`${cfg.apiBaseUrl}/api/csv/${id}`,{method:'DELETE',headers:apiHeaders()});if(!r.ok)throw Error(`Eliminazione fallita: HTTP ${r.status}`);await loadHistory()}
async function loadHistory(){const body=historyTable.querySelector('tbody');body.innerHTML='';historyError.classList.add('hidden');if(!cfg.apiBaseUrl||cfg.apiBaseUrl.includes('YOUR-WORKER'))return;try{const r=await fetch(`${cfg.apiBaseUrl}/api/csv`,{headers:apiHeaders()});if(!r.ok)throw Error(`HTTP ${r.status}`);const data=await r.json();data.items.forEach(i=>{const tr=document.createElement('tr');[i.fileName,new Date(i.createdAt).toLocaleString('it-IT'),i.recordCount.toLocaleString('it-IT'),bytes(i.size)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td)});const td=document.createElement('td'),box=document.createElement('div');box.className='row-actions';const d=document.createElement('button');d.textContent='Scarica';d.className='secondary';d.onclick=()=>apiDownload(i.id,i.fileName).catch(e=>alert(e.message));const x=document.createElement('button');x.textContent='Elimina';x.className='danger';x.onclick=()=>removeCSV(i.id).catch(e=>alert(e.message));box.append(d,x);td.appendChild(box);tr.appendChild(td);body.appendChild(tr)})}catch(e){historyError.textContent=`Storico non disponibile: ${e.message}`;historyError.classList.remove('hidden')}}
[startNameInput,prefixInput,endNameInput].forEach(i=>i.addEventListener('input',()=>fileNamePreview.textContent=outputName()));refreshHistoryBtn.onclick=loadHistory;
processBtn.onclick=async()=>{if(processing)return;errorBox.classList.add('hidden');resultBox.classList.add('hidden');const file=fileInput.files[0];if(!file){showError('Seleziona prima un file Excel .xlsx.');return}const path='/tmp/input.xlsx';setBusy(true,pyodide?'Elaborazione...':'Preparazione...');try{await pythonReady;pyodide.FS.writeFile(path,new Uint8Array(await file.arrayBuffer()));pyodide.globals.set('workbook_path_from_js',path);const result=JSON.parse(await pyodide.runPythonAsync('process_finrep(workbook_path_from_js)'));if(!result.records.length)throw Error('Nessun record valido trovato.');lastCSV=result.csv;lastFileName=outputName();render(result.records);recordCount.textContent=`Record totali generati: ${result.count} (anteprima delle prime 200 righe)`;resultBox.classList.remove('hidden');try{await archiveCSV(lastCSV,lastFileName,result.count)}catch(e){archiveStatus.textContent=`CSV generato, ma non archiviato: ${e.message}`}}catch(e){showError(`Errore durante l'elaborazione: ${e.message}`)}finally{setBusy(false);try{pyodide.FS.unlink(path)}catch{}try{pyodide.globals.delete('workbook_path_from_js')}catch{}}};
downloadBtn.onclick=()=>{if(!lastCSV)return;const u=URL.createObjectURL(new Blob(['\uFEFF',lastCSV],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=lastFileName;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)};setBusy(false);fileNamePreview.textContent=outputName();loadHistory();
